name: HopeItems
version: V2_2.2
author: Parozzz
main: me.parozzz.hopeitems.HopeItems
commands:
  items:
    aliases: [hpi]
    Usage: /items
    Description: Main Command
softdepend: [Vault, WorldGuard]

