name: HopeItems
version: V2_3.1
author: Parozzz
main: me.parozzz.hopeitems.HopeItems
commands:
  items:
    aliases: [hpi]
    Usage: /items
    Description: Main Command
softdepend: [Multiverse-Core, Vault, WorldGuard]

